name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
           docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
            mailhog \
               -api-bind-addr 127.0.0.1:8025 \
               -ui-bind-addr 127.0.0.1:8025 \
               -smtp-bind-addr 127.0.0.1:1025 
